language: node_js
node_js: 6
cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

deploy:
  local_dir: dist
  provider: firebase
  project: "iglo.tech"
  token:
    secure: $FIREBASE_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop
