language: node_js
node_js: 6
cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

deploy:
  provider: firebase
  project: "iglo-tech"
  token: $FIREBASE_TOKEN # Set in travis-ci.org dashboard
  skip_cleanup: true
  on:
    branch: develop
